#!/bin/bash

if [[ ! -d "/etc/letsencrypt/live" ]]
then
    (
        sleep 5; 
        certbot --nginx --noninteractive --agree-tos --email glitchless-letsencrypt@oleg.rocks --domains glitchless.ru,registry.glitchless.ru;
        sed -i "s/listen 443 ssl;/listen 443 ssl http2;/" /etc/nginx/sites-enabled/*;
    ) &
fi
    

nginx -g "daemon off;"