#!/bin/bash

[ -d "/etc/letsencrypt/live" ] || \
    (sleep 5; certbot --nginx --noninteractive --agree-tos --email glitchless-letsencrypt@oleg.rocks --domains glitchless.ru,registry.glitchless.ru) &

nginx -g "daemon off;"